create sequence SS_SEQ_CUSTOMERS;;

CREATE SEQUENCE SS_SEQ_ITEM_STORE_BAL;
CREATE SEQUENCE SS_SEQ_JOURNAL_HDR;
CREATE SEQUENCE SS_SEQ_JOURNAL_LINES;
CREATE SEQUENCE SS_SEQ_PURCHASE;
CREATE SEQUENCE SS_SEQ_SALES;
CREATE SEQUENCE SS_SEQ_TRANSFER;
CREATE SEQUENCE SS_SEQ_RECEIPT;
