create or replace PACKAGE SS_PKG_POSTING_ENGINE_C AS

PROCEDURE POST_PURCHASE ( P_PURCHASE_ID NUMBER ) ;

PROCEDURE POST_SALE ( P_SALES_ID NUMBER );

PROCEDURE POST_TRANSFER ( P_TRANSFER_ID NUMBER );

PROCEDURE POST_RECEIPT ( P_RECEIPT_ID NUMBER );

PROCEDURE POST_SUPPLIER_PAYMENT ( P_PAYMENT_ID NUMBER );

PROCEDURE CANCEL_PURCHASE (P_PURCHASE_ID NUMBER);

PROCEDURE CANCEL_SALE (P_SALES_ID NUMBER);

PROCEDURE CANCEL_TRANSFER (P_TRANSFER_ID NUMBER);


END SS_PKG_POSTING_ENGINE_C;