    CREATE TABLE "SS_COMPANIES" 
   (	"SS_COMPANY_ID" NUMBER, 
	"COMPANY_NAME" VARCHAR2(200), 
	"BASE_CURRENCY" VARCHAR2(10), 
	 PRIMARY KEY ("SS_COMPANY_ID")
  USING INDEX  ENABLE
   ) ;
  ------
    CREATE TABLE "SS_TAX_CODES" 
   (	"TAX_CODE" VARCHAR2(20), 
	"TAX_NAME" VARCHAR2(100), 
	"PERCENTAGE" NUMBER(5,2), 
	"ACCOUNT_ID" NUMBER, 
	 PRIMARY KEY ("TAX_CODE")
  USING INDEX  ENABLE
   ) ;
  ------
    CREATE TABLE "SS_FIN_PERIODS" 
   (	"SS_PERIOD_ID" NUMBER, 
	"PERIOD_NAME" VARCHAR2(30), 
	"DATE_FROM" DATE, 
	"DATE_TO" DATE, 
	"STATUS" VARCHAR2(20), 
	 CHECK (STATUS IN ('OPEN','CLOSED')) ENABLE, 
	 PRIMARY KEY ("SS_PERIOD_ID")
  USING INDEX  ENABLE
   ) ;
  ------
  CREATE TABLE "SS_STORES" 
   (	"SS_STORE_ID" NUMBER, 
	"STORE_CODE" VARCHAR2(30) NOT NULL ENABLE, 
	"STORE_NAME" VARCHAR2(200) NOT NULL ENABLE, 
	"STORE_TYPE" VARCHAR2(20), 
	"ACTIVE_YN" CHAR(1) DEFAULT 'Y', 
	"CREATED_AT" DATE DEFAULT SYSDATE, 
	 CHECK (STORE_TYPE IN ('MAIN','BRANCH')) ENABLE, 
	 CHECK (ACTIVE_YN IN ('Y','N')) ENABLE, 
	 PRIMARY KEY ("SS_STORE_ID")
  USING INDEX  ENABLE, 
	 UNIQUE ("STORE_CODE")
  USING INDEX  ENABLE
   ) ;
-----   
  CREATE TABLE "SS_CHART_OF_ACCOUNTS" 
   (	"SS_ACCOUNT_ID" NUMBER, 
	"PARENT_ID" NUMBER, 
	"ACCOUNT_CODE" VARCHAR2(30), 
	"ACCOUNT_NAME" VARCHAR2(200), 
	"ACCOUNT_TYPE" VARCHAR2(20), 
	"ACTIVE_YN" CHAR(1) DEFAULT 'Y', 
	 PRIMARY KEY ("SS_ACCOUNT_ID")
  USING INDEX  ENABLE, 
	 UNIQUE ("ACCOUNT_CODE")
  USING INDEX  ENABLE
   ) ;

  ALTER TABLE "SS_CHART_OF_ACCOUNTS" ADD CONSTRAINT "FK_ACC_PARENT" FOREIGN KEY ("PARENT_ID")
	  REFERENCES "SS_CHART_OF_ACCOUNTS" ("SS_ACCOUNT_ID") ENABLE;
------
CREATE TABLE "ACCOUNTS" (
    "ACC_NO"      NUMBER(7,0), 
    "ACC_PER"     NUMBER(7,0), 
    "ACC_TYPE"    NUMBER(1,0), 
    "ACC_AR"      VARCHAR2(60), 
    "ACC_EN"      VARCHAR2(60), 
    "ACC_CURR"    VARCHAR2(4), 
    "ACC_ICON"    VARCHAR2(10), 
    "ACC_LOC"     NUMBER(1,0), 
    "ACC_STATUS"  NUMBER(1,0), 
    "D_ADDRESS"   VARCHAR2(200), 
    "D_PHONE"     VARCHAR2(12), 
    "D_MOBILE"    VARCHAR2(12), 
    "D_WHATSAP"   VARCHAR2(12), 
    "D_EMAIL"     VARCHAR2(20), 
    "D_COMPANY"   VARCHAR2(50), 
    "D_TYPE"      NUMBER, 
    "INSURE_PER"  NUMBER(3,0),
    
    -- Primary Key Constraint
    CONSTRAINT "ACCOUNTS_PK" PRIMARY KEY ("ACC_NO"),
    
    -- Foreign Key Constraint (Self-Referencing)
    CONSTRAINT "ACCOUNTS_FK" FOREIGN KEY ("ACC_PER") 
        REFERENCES "ACCOUNTS" ("ACC_NO")
);
-----
  CREATE TABLE "SS_SUPPLIERS" 
   (	"SS_SUPPLIER_ID" NUMBER, 
	"SUPPLIER_CODE" VARCHAR2(30), 
	"SUPPLIER_NAME" VARCHAR2(200) NOT NULL ENABLE, 
	"PHONE" VARCHAR2(50), 
	"EMAIL" VARCHAR2(200), 
	"CREATED_AT" DATE DEFAULT SYSDATE, 
	 PRIMARY KEY ("SS_SUPPLIER_ID")
  USING INDEX  ENABLE, 
	 UNIQUE ("SUPPLIER_CODE") DISABLE
   ) ;
-----
CREATE TABLE "SS_SUPPLIER_PAYMENTS" (
    "SS_PAYMENT_ID" NUMBER, 
    "SUPPLIER_ID"   NUMBER NOT NULL, 
    "CURRENCY_CODE" VARCHAR2(10), 
    "EXCHANGE_RATE" NUMBER(18,6), 
    "AMOUNT_FC"     NUMBER(18,6), 
    "AMOUNT_LC"     NUMBER(18,6), 
    "TRX_DATE"      DATE DEFAULT SYSDATE, 
    "DESCRIPTION"   VARCHAR2(300), 
    "STATUS"        VARCHAR2(20), 

    -- Primary Key Constraint
    CONSTRAINT "SS_PAYMENT_PK" PRIMARY KEY ("SS_PAYMENT_ID"),

    -- Status Check Constraint
    CONSTRAINT "SS_PAYMENT_STATUS_CHK" 
        CHECK ("STATUS" IN ('DRAFT', 'POSTED', 'CANCELLED')),

    -- Foreign Key Constraint
    CONSTRAINT "FK_PAY_SUP" 
        FOREIGN KEY ("SUPPLIER_ID") 
        REFERENCES "SS_SUPPLIERS" ("SS_SUPPLIER_ID")
);
-----
  CREATE TABLE "SS_CUSTOMERS" 
   (	"SS_CUSTOMER_ID" NUMBER, 
	"CUSTOMER_CODE" VARCHAR2(30), 
	"CUSTOMER_NAME" VARCHAR2(200) NOT NULL ENABLE, 
	"PHONE" VARCHAR2(50), 
	"EMAIL" VARCHAR2(200), 
	"CREATED_AT" DATE DEFAULT SYSDATE, 
	 PRIMARY KEY ("SS_CUSTOMER_ID")
  USING INDEX  ENABLE, 
	 UNIQUE ("CUSTOMER_CODE") DISABLE
   ) ;
-----
  CREATE TABLE "JOURAL_MAS" 
   (	"JONO" NUMBER(20,0), 
	"JODATE" DATE, 
	"JOMEMO" VARCHAR2(300), 
	"JOTYPE" NUMBER(1,0), 
	"TONAME" VARCHAR2(50), 
	"CHQNO" VARCHAR2(20), 
	"CHQDATE" DATE, 
	"CHQBANK" VARCHAR2(100), 
	"INV_NO" NUMBER(20,0), 
	"TRHIL_CH" NUMBER(1,0) DEFAULT 0, 
	"SHIK_CH" NUMBER(1,0) DEFAULT 0, 
	"C_NO" NUMBER(2,0) DEFAULT 0, 
	"RATE" NUMBER(12,2) DEFAULT 1, 
	"RATE_DATE" DATE DEFAULT SYSDATE, 
	"USER_C" VARCHAR2(200), 
	"COMP_C" NUMBER(10,0), 
	 PRIMARY KEY ("JONO")
  USING INDEX  ENABLE
   ) ;
---
CREATE TABLE "JOURAL_DET" (
    "JONO"           NUMBER(20,0), 
    "ACC_NO"         NUMBER(7,0), 
    "DB"             NUMBER(15,2) DEFAULT 0, 
    "CR"             NUMBER(15,2) DEFAULT 0, 
    "COST_CENTER_NO" NUMBER       DEFAULT 0, 
    "JOMEMO"         VARCHAR2(200), 
    "CRS"            NUMBER(15,2) DEFAULT 0, 
    "DBS"            NUMBER(15,2) DEFAULT 0,

    -- Foreign Key to the ACCOUNTS table
    CONSTRAINT "JOURAL_DET_ACCOUNTS_FK" 
        FOREIGN KEY ("ACC_NO") 
        REFERENCES "ACCOUNTS" ("ACC_NO"),

    -- Foreign Key to the JOURAL_MAS (Master) table
    CONSTRAINT "JOURAL_DET_FK" 
        FOREIGN KEY ("JONO") 
        REFERENCES "JOURAL_MAS" ("JONO")
);
----
CREATE TABLE "SS_JOURNAL_HDR" (
    "SS_JOURNAL_ID" NUMBER, 
    "TRX_ID"         NUMBER, 
    "TRX_DATE"       DATE, 
    "DESCRIPTION"    VARCHAR2(500), 
    "TRX_TYPE_ID"    NUMBER, 
    "TRX_TYPE"       VARCHAR2(50), 

    -- Primary Key Constraint
    CONSTRAINT "SS_JOURNAL_HDR_PK" PRIMARY KEY ("SS_JOURNAL_ID"),

    -- Foreign Key Constraint
    CONSTRAINT "SS_JOURNAL_HDR_TRX_TYPE_FK" 
        FOREIGN KEY ("TRX_TYPE_ID") 
        REFERENCES "TRX_TYPE_LOOKUP" ("TRX_TYPE_ID")
);
----
CREATE TABLE "SS_PURCHASE_HDR" (
    "SS_PURCHASE_ID" NUMBER, 
    "SUPPLIER_ID"    NUMBER NOT NULL, 
    "STORE_ID"       NUMBER NOT NULL, 
    "INVOICE_NO"     VARCHAR2(50), 
    "CURRENCY_CODE"  VARCHAR2(10), 
    "EXCHANGE_RATE"  NUMBER(18,6), 
    "SUBTOTAL"       NUMBER(18,6), 
    "VAT_AMOUNT"     NUMBER(18,6), 
    "TOTAL_AMOUNT"   NUMBER(18,6), 
    "STATUS"         VARCHAR2(20), 
    "TRX_DATE"       DATE DEFAULT SYSDATE, 

    -- Primary Key Constraint
    CONSTRAINT "SS_PURCHASE_PK" PRIMARY KEY ("SS_PURCHASE_ID"),

    -- Foreign Key Constraint (Created in a DISABLED state as per your script)
    CONSTRAINT "FK_PUR_SUP" 
        FOREIGN KEY ("SUPPLIER_ID") 
        REFERENCES "SS_SUPPLIERS" ("SS_SUPPLIER_ID") 
        DISABLE
);
----
  CREATE TABLE "SS_PURCHASE_LINES1" 
   (	"SS_PUR_LINE_ID" NUMBER, 
	"PURCHASE_ID" NUMBER NOT NULL ENABLE, 
	"ITEM_ID" NUMBER NOT NULL ENABLE, 
	"QTY" NUMBER(18,6) NOT NULL ENABLE, 
	"UNIT_PRICE_FC" NUMBER(18,6), 
	"UNIT_PRICE_LC" NUMBER(18,6), 
	"LINE_SUBTOTAL" NUMBER(18,6), 
	"VAT_AMOUNT" NUMBER(18,6), 
	"LINE_TOTAL" NUMBER(18,6)
   ) ;
-----
CREATE OR REPLACE EDITIONABLE TRIGGER "TRG_PURCHASE_LINES_AMT" 
BEFORE INSERT OR UPDATE ON SS_PURCHASE_LINES1

FOR EACH ROW
BEGIN
   :NEW.LINE_TOTAL := NVL(:NEW.QTY,0) * NVL(:NEW.UNIT_PRICE_LC,0);
END;
/
ALTER TRIGGER "TRG_PURCHASE_LINES_AMT" ENABLE;
-----
  CREATE TABLE "SS_SALES_HDR" 
   (	"SS_SALES_ID" NUMBER, 
	"CUSTOMER_ID" NUMBER NOT NULL ENABLE, 
	"STORE_ID" NUMBER NOT NULL ENABLE, 
	"INVOICE_NO" VARCHAR2(50), 
	"CURRENCY_CODE" VARCHAR2(10), 
	"EXCHANGE_RATE" NUMBER(18,6), 
	"SUBTOTAL" NUMBER(18,6), 
	"VAT_AMOUNT" NUMBER(18,6), 
	"TOTAL_AMOUNT" NUMBER(18,6), 
	"STATUS" VARCHAR2(20), 
	"TRX_DATE" DATE DEFAULT SYSDATE, 
	 PRIMARY KEY ("SS_SALES_ID")
  USING INDEX  ENABLE
   ) ;

  ALTER TABLE "SS_SALES_HDR" ADD CONSTRAINT "FK_SALES_CUST" FOREIGN KEY ("CUSTOMER_ID")
	  REFERENCES "SS_CUSTOMERS" ("SS_CUSTOMER_ID") DISABLE;
-----
  CREATE TABLE "SS_SALES_LINES1" 
   (	"SS_SALES_LINE_ID" NUMBER, 
	"SALES_ID" NUMBER NOT NULL ENABLE, 
	"ITEM_ID" NUMBER NOT NULL ENABLE, 
	"QTY" NUMBER(18,6) NOT NULL ENABLE, 
	"UNIT_PRICE_FC" NUMBER(18,6), 
	"UNIT_PRICE_LC" NUMBER(18,6), 
	"COST_AMOUNT" NUMBER(18,6), 
	"PROFIT_AMOUNT" NUMBER(18,6), 
	"LINE_SUBTOTAL" NUMBER(18,6), 
	"VAT_AMOUNT" NUMBER(18,6), 
	"LINE_TOTAL" NUMBER(18,6)
   ) ;

  CREATE OR REPLACE EDITIONABLE TRIGGER "TRG_SALES_LINES_AMT" 
BEFORE INSERT OR UPDATE ON SS_SALES_LINES1

FOR EACH ROW
BEGIN
   :NEW.LINE_TOTAL := NVL(:NEW.QTY,0) * NVL(:NEW.UNIT_PRICE_LC,0);
END;
/
ALTER TRIGGER "TRG_SALES_LINES_AMT" ENABLE;
--------
  CREATE TABLE "SS_ITEM_COST" 
   (	"ITEM_ID" NUMBER, 
	"TOTAL_QTY" NUMBER, 
	"TOTAL_VALUE" NUMBER, 
	"AVG_COST" NUMBER, 
	 PRIMARY KEY ("ITEM_ID")
  USING INDEX  ENABLE
   ) ;
------
 CREATE TABLE "SS_ITEM_STORE_BAL" 
   (	"SS_BAL_ID" NUMBER, 
	"ITEM_ID" NUMBER NOT NULL ENABLE, 
	"STORE_ID" NUMBER NOT NULL ENABLE, 
	"QTY" NUMBER DEFAULT 0, 
	"AVG_COST" NUMBER(18,6) DEFAULT 0, 
	"TOTAL_VALUE" NUMBER(18,6) DEFAULT 0, 
	 PRIMARY KEY ("SS_BAL_ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "UK_BAL" UNIQUE ("ITEM_ID", "STORE_ID")
  USING INDEX  ENABLE
   ) ;

  ALTER TABLE "SS_ITEM_STORE_BAL" ADD CONSTRAINT "FK_BAL_ITEM" FOREIGN KEY ("ITEM_ID")
	  REFERENCES "SS_ITEMS" ("SS_ITEM_ID") DISABLE;
  ALTER TABLE "SS_ITEM_STORE_BAL" ADD CONSTRAINT "FK_BAL_STORE" FOREIGN KEY ("STORE_ID")
	  REFERENCES "SS_STORES" ("SS_STORE_ID") DISABLE;
----	  
  CREATE TABLE "SS_ACCOUNT_CONFIG" 
   (	"SS_ACC_CONF_ID" NUMBER, 
	"TRX_TYPE" VARCHAR2(30) NOT NULL ENABLE, 
	"ACCOUNT_ROLE" VARCHAR2(30) NOT NULL ENABLE, 
	"ACCOUNT_ID" NUMBER NOT NULL ENABLE, 
	 PRIMARY KEY ("SS_ACC_CONF_ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "UK_ACC_CONF" UNIQUE ("TRX_TYPE", "ACCOUNT_ROLE")
  USING INDEX  ENABLE
   ) ;

  ALTER TABLE "SS_ACCOUNT_CONFIG" ADD CONSTRAINT "FK_ACC_CONF_ACC" FOREIGN KEY ("ACCOUNT_ID")
	  REFERENCES "SS_CHART_OF_ACCOUNTS" ("SS_ACCOUNT_ID") ENABLE;
-----
	  CREATE TABLE "SS_STOCK_MOVEMENTS" 
   (	"SS_MOV_ID" NUMBER GENERATED BY DEFAULT AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"TRX_TYPE" VARCHAR2(30), 
	"TRX_ID" NUMBER, 
	"ITEM_ID" NUMBER, 
	"STORE_ID" NUMBER, 
	"QTY_IN" NUMBER, 
	"QTY_OUT" NUMBER, 
	"UNIT_COST" NUMBER, 
	"TOTAL_COST" NUMBER, 
	"TRX_DATE" DATE, 
	 PRIMARY KEY ("SS_MOV_ID")
  USING INDEX  ENABLE
   ) ;
---

    CREATE TABLE "SS_JOURNAL_LINES" 
   (	"SS_LINE_ID" NUMBER, 
	"JOURNAL_ID" NUMBER NOT NULL ENABLE, 
	"ACCOUNT_ID" NUMBER NOT NULL ENABLE, 
	"DEBIT" NUMBER(18,6) DEFAULT 0, 
	"CREDIT" NUMBER(18,6) DEFAULT 0, 
	 PRIMARY KEY ("SS_LINE_ID")
  USING INDEX  ENABLE
   ) ;

  ALTER TABLE "SS_JOURNAL_LINES" ADD CONSTRAINT "FK_JL_JH" FOREIGN KEY ("JOURNAL_ID")
	  REFERENCES "SS_JOURNAL_HDR" ("SS_JOURNAL_ID") ENABLE;
  ALTER TABLE "SS_JOURNAL_LINES" ADD CONSTRAINT "FK_JL_ACC" FOREIGN KEY ("ACCOUNT_ID")
	  REFERENCES "SS_CHART_OF_ACCOUNTS" ("SS_ACCOUNT_ID") ENABLE;

  CREATE INDEX "SS_IDX_JL_ACC" ON "SS_JOURNAL_LINES" ("ACCOUNT_ID") 
  ;
---
  CREATE TABLE "SS_SALES_RETURN_HDR" 
   (	"SS_SALES_RET_ID" NUMBER, 
	"SALES_ID" NUMBER, 
	"CUSTOMER_ID" NUMBER, 
	"STORE_ID" NUMBER, 
	"TRX_DATE" DATE DEFAULT SYSDATE, 
	"STATUS" VARCHAR2(20), 
	 PRIMARY KEY ("SS_SALES_RET_ID")
  USING INDEX  ENABLE
   ) ;

  ALTER TABLE "SS_SALES_RETURN_HDR" ADD CONSTRAINT "FK_SR_SALES" FOREIGN KEY ("SALES_ID")
	  REFERENCES "SS_SALES_HDR" ("SS_SALES_ID") ENABLE;
-----
  CREATE TABLE "SS_SALES_RETURN_LINES" 
   (	"SS_SALES_RET_LINE_ID" NUMBER, 
	"SALES_RET_ID" NUMBER NOT NULL ENABLE, 
	"ITEM_ID" NUMBER NOT NULL ENABLE, 
	"QTY" NUMBER(18,6), 
	"UNIT_PRICE" NUMBER(18,6), 
	"COST_AMOUNT" NUMBER(18,6), 
	"LINE_TOTAL" NUMBER(18,6), 
	 PRIMARY KEY ("SS_SALES_RET_LINE_ID")
  USING INDEX  ENABLE
   ) ;

  ALTER TABLE "SS_SALES_RETURN_LINES" ADD CONSTRAINT "FK_SR_LINE_HDR" FOREIGN KEY ("SALES_RET_ID")
	  REFERENCES "SS_SALES_RETURN_HDR" ("SS_SALES_RET_ID") ENABLE;
  ALTER TABLE "SS_SALES_RETURN_LINES" ADD CONSTRAINT "FK_SR_LINE_ITEM" FOREIGN KEY ("ITEM_ID")
	  REFERENCES "SS_ITEMS" ("SS_ITEM_ID") ENABLE;
---
  CREATE TABLE "SS_STOCK_MOVEMENTS1" 
   (	"SS_MOV_ID" NUMBER, 
	"TRX_TYPE" VARCHAR2(30), 
	"TRX_ID" NUMBER, 
	"ITEM_ID" NUMBER NOT NULL ENABLE, 
	"STORE_ID" NUMBER NOT NULL ENABLE, 
	"QTY_IN" NUMBER, 
	"QTY_OUT" NUMBER, 
	"UNIT_COST" NUMBER(18,6), 
	"TOTAL_COST" NUMBER(18,6), 
	"TRX_DATE" DATE
   ) ;
------
    CREATE TABLE "SS_TRANSFER_HDR" 
   (	"SS_TRANSFER_ID" NUMBER, 
	"FROM_STORE_ID" NUMBER NOT NULL ENABLE, 
	"TO_STORE_ID" NUMBER NOT NULL ENABLE, 
	"TRX_DATE" DATE DEFAULT SYSDATE, 
	"STATUS" VARCHAR2(20), 
	 PRIMARY KEY ("SS_TRANSFER_ID")
  USING INDEX  ENABLE
   ) ;

  ALTER TABLE "SS_TRANSFER_HDR" ADD CONSTRAINT "FK_TR_FROM" FOREIGN KEY ("FROM_STORE_ID")
	  REFERENCES "SS_STORES" ("SS_STORE_ID") DISABLE;
  ALTER TABLE "SS_TRANSFER_HDR" ADD CONSTRAINT "FK_TR_TO" FOREIGN KEY ("TO_STORE_ID")
	  REFERENCES "SS_STORES" ("SS_STORE_ID") DISABLE;
----
  CREATE TABLE "SS_TRANSFER_LINES" 
   (	"SS_TRANSFER_LINE_ID" NUMBER, 
	"TRANSFER_ID" NUMBER NOT NULL ENABLE, 
	"ITEM_ID" NUMBER NOT NULL ENABLE, 
	"QTY" NUMBER(18,6), 
	 PRIMARY KEY ("SS_TRANSFER_LINE_ID")
  USING INDEX  ENABLE
   ) ;

  ALTER TABLE "SS_TRANSFER_LINES" ADD CONSTRAINT "FK_TR_LINE_HDR" FOREIGN KEY ("TRANSFER_ID")
	  REFERENCES "SS_TRANSFER_HDR" ("SS_TRANSFER_ID") ENABLE;
  ALTER TABLE "SS_TRANSFER_LINES" ADD CONSTRAINT "FK_TR_LINE_ITEM" FOREIGN KEY ("ITEM_ID")
	  REFERENCES "SS_ITEMS" ("SS_ITEM_ID") ENABLE;
-----
 CREATE TABLE "SS_TRANSFER_LINES1" 
   (	"SS_TRANSFER_LINE_ID" NUMBER, 
	"TRANSFER_ID" NUMBER NOT NULL ENABLE, 
	"ITEM_ID" NUMBER NOT NULL ENABLE, 
	"QTY" NUMBER(18,6)
   ) ;
------
    CREATE TABLE "SS_RECEIPTS" 
   (	"SS_RECEIPT_ID" NUMBER, 
	"CUSTOMER_ID" NUMBER NOT NULL ENABLE, 
	"CURRENCY_CODE" VARCHAR2(10), 
	"EXCHANGE_RATE" NUMBER(18,6), 
	"AMOUNT_FC" NUMBER(18,6), 
	"AMOUNT_LC" NUMBER(18,6), 
	"TRX_DATE" DATE DEFAULT SYSDATE, 
	"DESCRIPTION" VARCHAR2(300), 
	"STATUS" VARCHAR2(20), 
	 PRIMARY KEY ("SS_RECEIPT_ID")
  USING INDEX  ENABLE, 
	 CHECK (STATUS IN ('DRAFT','POSTED','CANCELLED')) ENABLE
   ) ;

  ALTER TABLE "SS_RECEIPTS" ADD CONSTRAINT "FK_RC_CUST" FOREIGN KEY ("CUSTOMER_ID")
	  REFERENCES "SS_CUSTOMERS" ("SS_CUSTOMER_ID") DISABLE;
----	  
     CREATE TABLE "SS_ITEMS" 
   (	"SS_ITEM_ID" NUMBER, 
	"ITEM_CODE" VARCHAR2(50) NOT NULL ENABLE, 
	"ITEM_NAME" VARCHAR2(300) NOT NULL ENABLE, 
	"ITEM_TYPE" VARCHAR2(20), 
	"BARCODE" VARCHAR2(100), 
	"TRACK_BATCH_YN" CHAR(1) DEFAULT 'N', 
	"TRACK_EXPIRY_YN" CHAR(1) DEFAULT 'N', 
	"ACTIVE_YN" CHAR(1) DEFAULT 'Y', 
	"CREATED_AT" DATE DEFAULT SYSDATE, 
	 CHECK (ITEM_TYPE IN ('PRODUCT','SERVICE')) ENABLE, 
	 CHECK (TRACK_BATCH_YN IN ('Y','N')) ENABLE, 
	 CHECK (TRACK_EXPIRY_YN IN ('Y','N')) ENABLE, 
	 CHECK (ACTIVE_YN IN ('Y','N')) ENABLE, 
	 PRIMARY KEY ("SS_ITEM_ID")
  USING INDEX  ENABLE, 
	 UNIQUE ("ITEM_CODE")
  USING INDEX  ENABLE
   ) ;
   ----
     CREATE TABLE "SS_AUDIT_LOG" 
   (	"SS_AUDIT_ID" NUMBER, 
	"TABLE_NAME" VARCHAR2(50), 
	"RECORD_ID" NUMBER, 
	"ACTION_TYPE" VARCHAR2(20), 
	"OLD_DATA" CLOB, 
	"NEW_DATA" CLOB, 
	"CREATED_BY" VARCHAR2(100), 
	"CREATED_AT" DATE DEFAULT SYSDATE, 
	 PRIMARY KEY ("SS_AUDIT_ID")
  USING INDEX  ENABLE
   ) ;
   ----